### ISSUE TITLE
Can't access the laradock command

### ISSUE THREAD

**Issue by g33kidd** [logaretm/laradock-cli#1]
Not sure if it has something to do with my setup, but I've done `npm install -g laradock-cli` and my system isn't recognizing the laradock command. I am using zsh, but I've installed many npm cli tools in the past and have had no issues.

**Comment by logaretm** [comment]
nah I messed something up not sure what. It works locally on my machine (Windows). I will check it out and hopefully I can figure it out.

**Comment by g33kidd** [comment]
My fault... I don't know what exactly happened, but I have it working! Whoops!
